#!/usr/bin/env python3
"""Offline safety checks for live qualification harnesses.

These cases execute each guard with unarmed or missing authority, and require refusal before
creating evidence or contacting a runtime. Guest behaviour is covered by the live gates and
runtime suites; searching harness source text does not prove it.
"""

from __future__ import annotations

import os
from pathlib import Path
import subprocess
import sys
import tempfile
import unittest

ROOT = Path(__file__).resolve().parents[2]

# (harness, CLI arguments, environment overrides, refusal reason, expected exit status)
CASES = (('act-compatibility-gate.sh',
  ('--socket',
   '{root}/missing.sock',
   '--docker',
   '/missing/docker',
   '--runner-image',
   'example.invalid/runner@sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
   '--workroot',
   '{root}/evidence'),
  {},
  'requires --confirm',
  2),
 ('bind-file-coherence-gate.sh',
  ('--socket',
   '{root}/missing.sock',
   '--docker',
   '/missing/docker',
   '--image',
   'invalid',
   '--workroot',
   '{root}/must-not-exist'),
  {'DORY_BIND_COHERENCE_CONFIRM': ''},
  'requires --confirm',
  2),
 ('competitor-runtime-regression-gate.sh',
  ('--socket',
   '{root}/missing.sock',
   '--state-dir',
   '{root}/missing-state',
   '--docker',
   '/missing/docker',
   '--workroot',
   '{root}/must-not-exist'),
  {},
  'requires --confirm',
  2),
 ('data-disk-growth-gate.sh',
  ('--runtime',
   '/missing/runtime',
   '--docker',
   '/missing/docker',
   '--image',
   'invalid',
   '--workroot',
   '{root}/must-not-exist'),
  {'DORY_DATA_DISK_RUNTIME_HOME': '{root}/runtime-must-not-exist'},
  'requires --confirm',
  2),
 ('data-drive-volume-identity-gate.sh',
  ('--dory-hv', '/missing/dory-hv', '--workroot', '{root}/must-not-exist'),
  {},
  'requires --confirm',
  2),
 ('default-platform-image-gate.sh',
  ('--socket',
   '{root}/missing.sock',
   '--docker',
   '/missing/docker',
   '--image',
   'invalid',
   '--workroot',
   '{root}/must-not-exist'),
  {},
  'requires --confirm',
  2),
 ('devcontainers-compatibility-gate.sh',
  ('--socket',
   '{root}/missing.sock',
   '--docker',
   '/missing/docker',
   '--version',
   '0.87.0',
   '--image',
   'example.invalid/alpine@sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
   '--workroot',
   '{root}/evidence'),
  {},
  'requires --confirm',
  2),
 ('ecr-registry-retry-gate.sh',
  ('--socket',
   '{root}/missing.sock',
   '--docker',
   '/missing/docker',
   '--base-image',
   'invalid',
   '--registry',
   'invalid',
   '--repository',
   'invalid',
   '--region',
   'invalid',
   '--workroot',
   '{root}/must-not-exist'),
  {},
  'requires --confirm',
  2),
 ('external-volume-bind-gate.sh',
  ('--socket',
   '{root}/missing.sock',
   '--docker',
   '/missing/docker',
   '--dory',
   '/missing/dory',
   '--state-dir',
   '{root}/state',
   '--path',
   '{root}/volume',
   '--image',
   'example.invalid/alpine@sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
   '--workroot',
   '{root}/evidence'),
  {},
  'requires --confirm',
  2),
 ('gvproxy-qemu-switch-gate.py',
  ('/missing/gvproxy', '--workroot', '{root}/must-not-exist'),
  {},
  'requires --confirm',
  None),
 ('host-network-integrity-gate.sh',
  ('--socket',
   '{root}/missing.sock',
   '--docker',
   '/missing/docker',
   '--app',
   '/missing/Dory.app',
   '--workroot',
   '{root}/evidence'),
  {'DORY_NETWORK_INTEGRITY_IMAGE': 'example.invalid/alpine@sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'},
  'physical sleep requires --confirm-physical-sleep',
  2),
 ('kubernetes-tooling-compatibility-gate.sh',
  ('--socket',
   '{root}/missing.sock',
   '--docker',
   '/missing/docker',
   '--kubectl',
   '/missing/kubectl',
   '--workroot',
   '{root}/must-not-exist',
   '--k3s-image',
   'invalid',
   '--workload-image',
   'invalid'),
  {},
  'requires --confirm',
  2),
 ('live-orbstack-migration-smoke.sh',
  (),
  {'DORY_LIVE_MIGRATION_BASE_IMAGE': 'example.invalid/alpine@sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
   'DORY_LIVE_DOCKER_BIN': '/missing/docker'},
  'DORY_LIVE_MIGRATION_CONFIRMED',
  2),
 ('localstack-compatibility-gate.sh',
  ('--socket',
   '{root}/missing.sock',
   '--docker',
   '/missing/docker',
   '--image',
   'example.invalid/localstack@sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
   '--workroot',
   '{root}/must-not-exist'),
  {},
  'requires --confirm',
  2),
 ('long-lived-network-soak.sh',
  ('--socket',
   '{root}/missing.sock',
   '--docker',
   '/missing/docker',
   '--image',
   'invalid',
   '--workroot',
   '{root}/must-not-exist'),
  {},
  'requires --confirm',
  2),
 ('managed-data-drive-gate.sh',
  ('--runtime',
   '/missing/runtime',
   '--docker',
   '/missing/docker',
   '--workroot',
   '{root}/must-not-exist'),
  {},
  'requires --confirm',
  2),
 ('native-ipv6-gate.sh',
  ('--dory-hv',
   '/missing/dory-hv',
   '--gvproxy',
   '/missing/gvproxy',
   '--kernel',
   '/missing/kernel',
   '--rootfs',
   '/missing/rootfs',
   '--docker',
   '/missing/docker',
   '--workroot',
   '{root}/must-not-exist'),
  {},
  'requires --confirm',
  2),
 ('nonnative-arch-pacman-gate.sh',
  ('--socket',
   '{root}/missing.sock',
   '--docker',
   '/missing/docker',
   '--base-image',
   'invalid',
   '--workroot',
   '{root}/must-not-exist'),
  {},
  'requires --confirm',
  2),
 ('nonnative-exec-conformance-gate.sh',
  ('--socket',
   '{root}/missing.sock',
   '--docker',
   '/missing/docker',
   '--base-image',
   'invalid',
   '--native-image',
   'invalid',
   '--workroot',
   '{root}/must-not-exist'),
  {},
  'requires --confirm',
  2),
 ('nonnative-mmdebstrap-gate.sh',
  ('--socket',
   '{root}/missing.sock',
   '--docker',
   '/missing/docker',
   '--base-image',
   'invalid',
   '--workroot',
   '{root}/must-not-exist'),
  {},
  'requires --confirm',
  2),
 ('nonnative-nix-gc-gate.sh',
  ('--socket',
   '{root}/missing.sock',
   '--docker',
   '/missing/docker',
   '--image',
   'invalid',
   '--workroot',
   '{root}/must-not-exist'),
  {},
  'requires --confirm',
  2),
 ('offline-bundled-boot-gate.sh',
  ('--runtime', '{root}/missing-runtime', '--workroot', '{root}/must-not-exist'),
  {},
  'requires --confirm',
  2),
 ('private-registry-auth-gate.sh',
  ('--socket',
   '{root}/missing.sock',
   '--docker',
   '/missing/docker',
   '--buildx',
   '/missing/buildx',
   '--base-image',
   'invalid',
   '--source-commit',
   'invalid',
   '--workroot',
   '{root}/must-not-exist'),
  {},
  'requires --confirm',
  2),
 ('prune-safety-gate.sh',
  ('--socket',
   '{root}/missing.sock',
   '--docker',
   '/missing/docker',
   '--base-image',
   'invalid',
   '--source-commit',
   'invalid',
   '--workroot',
   '{root}/must-not-exist'),
  {},
  'destructive prune requires --confirm',
  2),
 ('testcontainers-compatibility-gate.sh',
  ('--socket',
   '{root}/missing.sock',
   '--docker',
   '/missing/docker',
   '--image',
   'example.invalid/workload@sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
   '--ryuk-image',
   'example.invalid/ryuk@sha256:bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
   '--workroot',
   '{root}/must-not-exist'),
  {},
  'requires --confirm',
  2),
 ('tilt-compose-compatibility-gate.sh',
  ('--socket',
   '{root}/missing.sock',
   '--docker',
   '/missing/docker',
   '--compose',
   '/missing/docker-compose',
   '--image',
   'example.invalid/alpine@sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
   '--workroot',
   '{root}/must-not-exist'),
  {},
  'requires --confirm',
  2))


class QualificationHarnessSafetyTests(unittest.TestCase):
    def test_unarmed_harnesses_refuse_before_runtime_or_filesystem_mutation(self) -> None:
        for name, arguments, overrides, refusal, exit_status in CASES:
            with self.subTest(harness=name), tempfile.TemporaryDirectory() as temporary:
                root = Path(temporary)
                gate = ROOT / "scripts" / name
                if gate.suffix == ".sh":
                    subprocess.run(["bash", "-n", str(gate)], check=True, timeout=10)
                command = [sys.executable if gate.suffix == ".py" else "bash", str(gate)]
                command.extend(value.format(root=temporary) for value in arguments)
                # An existing live campaign's environment cannot arm an offline test.
                environment = {key: value for key, value in os.environ.items()
                               if not key.startswith("DORY_")}
                environment.update(HOME=temporary)
                environment.update({key: value.format(root=temporary)
                                    for key, value in overrides.items()})
                result = subprocess.run(
                    command, cwd=ROOT, env=environment, text=True,
                    capture_output=True, check=False, timeout=10,
                )
                if exit_status is None:
                    self.assertNotEqual(result.returncode, 0, result.stderr)
                else:
                    self.assertEqual(result.returncode, exit_status, result.stderr)
                self.assertIn(refusal, result.stderr)
                self.assertEqual(list(root.iterdir()), [], "unarmed gate wrote to its workroot")


if __name__ == "__main__":
    unittest.main()
