apiVersion: batch/v1
kind: Job
metadata:
  name: readiness-client
  namespace: dory-readiness
  labels:
    dev.dory.readiness: "true"
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        dev.dory.readiness: "true"
    spec:
      restartPolicy: Never
      containers:
        - name: client
          image: alpine:3.20
          command:
            - sh
            - -c
            - wget -qO- http://readiness-web.dory-readiness.svc.cluster.local | grep -q k8s-ok

