import Foundation
import Virtualization

public enum DoryVZMacResourcePlanError: Error, Sendable, Equatable, CustomStringConvertible {
    case invalidCPUCount(requested: Int, minimum: Int, maximum: Int)
    case invalidMemoryBytes(requested: UInt64, minimum: UInt64, maximum: UInt64)
    case memoryMustBeMiBAligned(UInt64)
    case diskTooSmall(requested: UInt64, minimum: UInt64)
    case diskResizeMustGrow(current: UInt64, requested: UInt64)
    case invalidDisplay(index: Int)
    case tooManyDisplays(requested: Int, maximum: Int)
    case tooManyDataDisks(requested: Int, maximum: Int)
    case invalidDataDisk(index: Int, requested: UInt64, minimum: UInt64)

    public var description: String {
        switch self {
        case .invalidCPUCount(let requested, let minimum, let maximum):
            "VZMac CPU count \(requested) is outside \(minimum)...\(maximum)"
        case .invalidMemoryBytes(let requested, let minimum, let maximum):
            "VZMac memory \(requested) is outside \(minimum)...\(maximum) bytes"
        case .memoryMustBeMiBAligned(let requested):
            "VZMac memory \(requested) must be aligned to one MiB"
        case .diskTooSmall(let requested, let minimum):
            "VZMac disk \(requested) is smaller than the \(minimum)-byte minimum"
        case .diskResizeMustGrow(let current, let requested):
            "VZMac disk resize must grow from \(current) bytes, not \(requested) bytes"
        case .invalidDisplay(let index):
            "VZMac display \(index) has an invalid geometry or pixel density"
        case .tooManyDisplays(let requested, let maximum):
            "VZMac requested \(requested) displays; at most \(maximum) are supported"
        case .tooManyDataDisks(let requested, let maximum):
            "VZMac requested \(requested) data disks; at most \(maximum) are supported"
        case .invalidDataDisk(let index, let requested, let minimum):
            "VZMac data disk \(index) size \(requested) is smaller than the \(minimum)-byte minimum or is not sector aligned"
        }
    }
}

public struct DoryVZMacDisplay: Codable, Sendable, Equatable {
    public let widthInPixels: Int
    public let heightInPixels: Int
    public let pixelsPerInch: Int

    public init(widthInPixels: Int, heightInPixels: Int, pixelsPerInch: Int) {
        self.widthInPixels = widthInPixels
        self.heightInPixels = heightInPixels
        self.pixelsPerInch = pixelsPerInch
    }
}

/// A durable, bundle-owned virtio block image. The filename is generated by the resource plan
/// and not accepted from callers, so a manifest cannot redirect a VZ attachment outside its
/// machine bundle.
public struct DoryVZMacDataDisk: Codable, Sendable, Equatable {
    public let fileName: String
    public let byteCount: UInt64

    fileprivate init(index: Int, byteCount: UInt64) {
        fileName = String(format: "data-%02d.img", index + 1)
        self.byteCount = byteCount
    }

    fileprivate var isValidFileName: Bool {
        let bytes = fileName.utf8
        return bytes.count == 11
            && fileName.hasPrefix("data-")
            && fileName.hasSuffix(".img")
            && fileName.dropFirst(5).dropLast(4).allSatisfy(\.isNumber)
    }
}

public struct DoryVZMacResourcePlan: Codable, Sendable, Equatable {
    public static let mebibyte: UInt64 = 1_024 * 1_024
    public static let gibibyte: UInt64 = 1_024 * 1_024 * 1_024
    public static let minimumDiskBytes: UInt64 = 64 * gibibyte
    public static let minimumDataDiskBytes: UInt64 = gibibyte
    public static let maximumDataDiskCount = 8
    /// Keep presentation, resource admission, and persisted graphics topology bounded together.
    /// Virtualization.framework supports separate views for each configured display.
    public static let maximumDisplayCount = 8

    public let cpuCount: Int
    public let memoryBytes: UInt64
    public let diskBytes: UInt64
    public let displays: [DoryVZMacDisplay]
    public let dataDisks: [DoryVZMacDataDisk]

    private enum CodingKeys: String, CodingKey {
        case cpuCount, memoryBytes, diskBytes, displays, dataDisks
    }

    public init(
        requestedCPUCount: Int?,
        requestedMemoryBytes: UInt64?,
        requestedDiskBytes: UInt64,
        requestedDisplays: [DoryVZMacDisplay]?,
        requestedDataDiskBytes: [UInt64] = [],
        minimumCPUCount: Int,
        minimumMemoryBytes: UInt64,
        maximumCPUCount: Int,
        maximumMemoryBytes: UInt64
    ) throws {
        let cpuCount = requestedCPUCount ?? minimumCPUCount
        guard cpuCount >= minimumCPUCount, cpuCount <= maximumCPUCount else {
            throw DoryVZMacResourcePlanError.invalidCPUCount(
                requested: cpuCount,
                minimum: minimumCPUCount,
                maximum: maximumCPUCount
            )
        }
        let memoryBytes = requestedMemoryBytes ?? minimumMemoryBytes
        guard memoryBytes >= minimumMemoryBytes, memoryBytes <= maximumMemoryBytes else {
            throw DoryVZMacResourcePlanError.invalidMemoryBytes(
                requested: memoryBytes,
                minimum: minimumMemoryBytes,
                maximum: maximumMemoryBytes
            )
        }
        guard memoryBytes.isMultiple(of: Self.mebibyte) else {
            throw DoryVZMacResourcePlanError.memoryMustBeMiBAligned(memoryBytes)
        }
        guard requestedDiskBytes >= Self.minimumDiskBytes else {
            throw DoryVZMacResourcePlanError.diskTooSmall(
                requested: requestedDiskBytes,
                minimum: Self.minimumDiskBytes
            )
        }
        self.cpuCount = cpuCount
        self.memoryBytes = memoryBytes
        self.diskBytes = requestedDiskBytes
        let displays = requestedDisplays ?? [Self.defaultDisplay]
        guard !displays.isEmpty else {
            throw DoryVZMacResourcePlanError.invalidDisplay(index: 0)
        }
        guard displays.count <= Self.maximumDisplayCount else {
            throw DoryVZMacResourcePlanError.tooManyDisplays(
                requested: displays.count,
                maximum: Self.maximumDisplayCount
            )
        }
        for (index, display) in displays.enumerated() {
            guard display.widthInPixels > 0,
                  display.heightInPixels > 0,
                  display.pixelsPerInch > 0 else {
                throw DoryVZMacResourcePlanError.invalidDisplay(index: index)
            }
        }
        self.displays = displays
        guard requestedDataDiskBytes.count <= Self.maximumDataDiskCount else {
            throw DoryVZMacResourcePlanError.tooManyDataDisks(
                requested: requestedDataDiskBytes.count,
                maximum: Self.maximumDataDiskCount
            )
        }
        for (index, size) in requestedDataDiskBytes.enumerated() {
            guard size >= Self.minimumDataDiskBytes, size.isMultiple(of: 512) else {
                throw DoryVZMacResourcePlanError.invalidDataDisk(
                    index: index,
                    requested: size,
                    minimum: Self.minimumDataDiskBytes
                )
            }
        }
        dataDisks = requestedDataDiskBytes.enumerated().map {
            DoryVZMacDataDisk(index: $0.offset, byteCount: $0.element)
        }
    }

    public init(
        requestedCPUCount: Int?,
        requestedMemoryBytes: UInt64?,
        requestedDiskBytes: UInt64,
        requirements: VZMacOSConfigurationRequirements
    ) throws {
        try self.init(
            requestedCPUCount: requestedCPUCount,
            requestedMemoryBytes: requestedMemoryBytes,
            requestedDiskBytes: requestedDiskBytes,
            requestedDisplays: nil,
            requestedDataDiskBytes: [],
            minimumCPUCount: requirements.minimumSupportedCPUCount,
            minimumMemoryBytes: requirements.minimumSupportedMemorySize,
            maximumCPUCount: VZVirtualMachineConfiguration.maximumAllowedCPUCount,
            maximumMemoryBytes: VZVirtualMachineConfiguration.maximumAllowedMemorySize
        )
    }

    static var defaultDisplay: DoryVZMacDisplay {
        DoryVZMacDisplay(widthInPixels: 1_920, heightInPixels: 1_080, pixelsPerInch: 144)
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        cpuCount = try container.decode(Int.self, forKey: .cpuCount)
        memoryBytes = try container.decode(UInt64.self, forKey: .memoryBytes)
        diskBytes = try container.decode(UInt64.self, forKey: .diskBytes)
        displays = try container.decode([DoryVZMacDisplay].self, forKey: .displays)
        dataDisks = try container.decodeIfPresent([DoryVZMacDataDisk].self, forKey: .dataDisks) ?? []
        guard diskBytes >= Self.minimumDiskBytes else {
            throw DoryVZMacResourcePlanError.diskTooSmall(
                requested: diskBytes,
                minimum: Self.minimumDiskBytes
            )
        }
        guard !displays.isEmpty, displays.count <= Self.maximumDisplayCount else {
            throw DoryVZMacResourcePlanError.tooManyDisplays(
                requested: displays.count,
                maximum: Self.maximumDisplayCount
            )
        }
        for (index, display) in displays.enumerated() {
            guard display.widthInPixels > 0,
                  display.heightInPixels > 0,
                  display.pixelsPerInch > 0 else {
                throw DoryVZMacResourcePlanError.invalidDisplay(index: index)
            }
        }
        guard dataDisks.count <= Self.maximumDataDiskCount else {
            throw DoryVZMacResourcePlanError.tooManyDataDisks(
                requested: dataDisks.count,
                maximum: Self.maximumDataDiskCount
            )
        }
        for (index, disk) in dataDisks.enumerated() {
            guard disk.fileName == DoryVZMacDataDisk(index: index, byteCount: disk.byteCount).fileName,
                  disk.isValidFileName,
                  disk.byteCount >= Self.minimumDataDiskBytes,
                  disk.byteCount.isMultiple(of: 512) else {
                throw DoryVZMacResourcePlanError.invalidDataDisk(
                    index: index,
                    requested: disk.byteCount,
                    minimum: Self.minimumDataDiskBytes
                )
            }
        }
    }

    /// VZ disk-image attachments can grow while stopped, but they cannot safely shrink because
    /// the guest partition map and APFS container own the existing tail blocks.
    public func growingSystemDisk(to requestedDiskBytes: UInt64) throws -> Self {
        guard requestedDiskBytes > diskBytes else {
            throw DoryVZMacResourcePlanError.diskResizeMustGrow(
                current: diskBytes,
                requested: requestedDiskBytes
            )
        }
        guard requestedDiskBytes >= Self.minimumDiskBytes else {
            throw DoryVZMacResourcePlanError.diskTooSmall(
                requested: requestedDiskBytes,
                minimum: Self.minimumDiskBytes
            )
        }
        return try Self(
            requestedCPUCount: cpuCount,
            requestedMemoryBytes: memoryBytes,
            requestedDiskBytes: requestedDiskBytes,
            requestedDisplays: displays,
            requestedDataDiskBytes: dataDisks.map(\.byteCount),
            minimumCPUCount: cpuCount,
            minimumMemoryBytes: memoryBytes,
            maximumCPUCount: cpuCount,
            maximumMemoryBytes: memoryBytes
        )
    }

    /// Data images follow the same grow-only rule as the system image. The stable filename at
    /// each index remains unchanged, so a resize cannot redirect an existing guest attachment.
    public func growingDataDisk(at index: Int, to requestedDiskBytes: UInt64) throws -> Self {
        guard dataDisks.indices.contains(index) else {
            throw DoryVZMacResourcePlanError.invalidDataDisk(
                index: index,
                requested: requestedDiskBytes,
                minimum: Self.minimumDataDiskBytes
            )
        }
        let existing = dataDisks[index]
        guard requestedDiskBytes > existing.byteCount,
              requestedDiskBytes >= Self.minimumDataDiskBytes,
              requestedDiskBytes.isMultiple(of: 512) else {
            throw DoryVZMacResourcePlanError.invalidDataDisk(
                index: index,
                requested: requestedDiskBytes,
                minimum: Self.minimumDataDiskBytes
            )
        }
        var requestedDataDiskBytes = dataDisks.map(\.byteCount)
        requestedDataDiskBytes[index] = requestedDiskBytes
        return try Self(
            requestedCPUCount: cpuCount,
            requestedMemoryBytes: memoryBytes,
            requestedDiskBytes: diskBytes,
            requestedDisplays: displays,
            requestedDataDiskBytes: requestedDataDiskBytes,
            minimumCPUCount: cpuCount,
            minimumMemoryBytes: memoryBytes,
            maximumCPUCount: cpuCount,
            maximumMemoryBytes: memoryBytes
        )
    }
}
