// SPDX-License-Identifier: BSD-2-Clause-Patent

#ifndef DORY_PC_FIRMWARE_CONFIGURATION_H_
#define DORY_PC_FIRMWARE_CONFIGURATION_H_

#define DORY_PC_CONFIGURATION_MAGIC               0x3146435059524F44ULL
#define DORY_PC_CONFIGURATION_VERSION             1U
#define DORY_PC_CONFIGURATION_HEADER_SIZE         144U
#define DORY_PC_CONFIGURATION_MAGIC_OFFSET        0U
#define DORY_PC_CONFIGURATION_VERSION_OFFSET      8U
#define DORY_PC_CONFIGURATION_HEADER_SIZE_OFFSET  12U
#define DORY_PC_CONFIGURATION_MACHINE_VERSION     16U
#define DORY_PC_CONFIGURATION_FLAGS_OFFSET        20U
#define DORY_PC_CONFIGURATION_TOTAL_RAM_OFFSET    24U
#define DORY_PC_CONFIGURATION_LOW_RAM_OFFSET      32U
#define DORY_PC_CONFIGURATION_HIGH_RAM_OFFSET     40U
#define DORY_PC_CONFIGURATION_CPU_COUNT_OFFSET    48U
#define DORY_PC_CONFIGURATION_PCI_SEGMENT_OFFSET  52U
#define DORY_PC_CONFIGURATION_ECAM_BASE_OFFSET    56U
#define DORY_PC_CONFIGURATION_ECAM_SIZE_OFFSET    64U
#define DORY_PC_CONFIGURATION_MMIO_BASE_OFFSET    72U
#define DORY_PC_CONFIGURATION_MMIO_SIZE_OFFSET    80U
#define DORY_PC_CONFIGURATION_RSDP_OFFSET         88U
#define DORY_PC_CONFIGURATION_SMBIOS_OFFSET       96U
#define DORY_PC_CONFIGURATION_VARIABLE_BASE       104U
#define DORY_PC_CONFIGURATION_VARIABLE_SIZE       112U
#define DORY_PC_CONFIGURATION_FIRMWARE_BASE       120U
#define DORY_PC_CONFIGURATION_FIRMWARE_SIZE       128U
#define DORY_PC_CONFIGURATION_HIGH_RAM_BASE       136U
#define DORY_PC_CONFIGURATION_FLAG_BOOT_PROBE     0x00000001U

#endif
